name: Simple CI

on:
  push:
    branches: [main]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks:v8.18.3
    steps:
      - uses: actions/checkout@v3
      - run: pwd && ls -la && gitleaks version && gitleaks detect -v --no-banner --source=. --redact=50
